services:
  ipfs-node1:
    image: ipfs/go-ipfs:latest
    container_name: ipfs-node1
    ports:
      - "5011:5001" # API
      - "8090:8080" # Gateway
      - "4011:4001" # Swarm
    volumes:
      - ./ipfs-data/node1:/data/ipfs:z
    restart: unless-stopped
    user: root

  ipfs-node2:
    image: ipfs/go-ipfs:latest
    container_name: ipfs-node2
    ports:
      - "5002:5001"
      - "8081:8080"
      - "4002:4001"
    volumes:
      - ./ipfs-data/node2:/data/ipfs:z
    restart: unless-stopped
    user: root

  ipfs-node3:
    image: ipfs/go-ipfs:latest
    container_name: ipfs-node3
    ports:
      - "5003:5001"
      - "8082:8080"
      - "4003:4001"
    volumes:
      - ./ipfs-data/node3:/data/ipfs:z
    restart: unless-stopped
    user: root

  ipfs-node4:
    image: ipfs/go-ipfs:latest
    container_name: ipfs-node4
    ports:
      - "5004:5001"
      - "8083:8080"
      - "4004:4001"
    volumes:
      - ./ipfs-data/node4:/data/ipfs:z
    restart: unless-stopped
    user: root

  ipfs-node5:
    image: ipfs/go-ipfs:latest
    container_name: ipfs-node5
    ports:
      - "5005:5001"
      - "8084:8080"
      - "4005:4001"
    volumes:
      - ./ipfs-data/node5:/data/ipfs:z
    restart: unless-stopped
    user: root

  ipfs-node6:
    image: ipfs/go-ipfs:latest
    container_name: ipfs-node6
    ports:
      - "5006:5001"
      - "8085:8080"
      - "4006:4001"
    volumes:
      - ./ipfs-data/node6:/data/ipfs:z
    restart: unless-stopped
    user: root

  ipfs-node7:
    image: ipfs/go-ipfs:latest
    container_name: ipfs-node7
    ports:
      - "5007:5001"
      - "8086:8080"
      - "4007:4001"
    volumes:
      - ./ipfs-data/node7:/data/ipfs:z
    restart: unless-stopped
    user: root

  ipfs-node8:
    image: ipfs/go-ipfs:latest
    container_name: ipfs-node8
    ports:
      - "5008:5001"
      - "8087:8080"
      - "4008:4001"
    volumes:
      - ./ipfs-data/node8:/data/ipfs:z
    restart: unless-stopped
    user: root

  ipfs-node9:
    image: ipfs/go-ipfs:latest
    container_name: ipfs-node9
    ports:
      - "5009:5001"
      - "8088:8080"
      - "4009:4001"
    volumes:
      - ./ipfs-data/node9:/data/ipfs:z
    restart: unless-stopped
    user: root

  ipfs-node10:
    image: ipfs/go-ipfs:latest
    container_name: ipfs-node10
    ports:
      - "5010:5001"
      - "8089:8080"
      - "4010:4001"
    volumes:
      - ./ipfs-data/node10:/data/ipfs:z
    restart: unless-stopped
    user: root

  cluster-node1:
    container_name: cluster-node1
    image: ipfs/ipfs-cluster:latest
    restart: unless-stopped
    volumes:
      - ./cluster-data/cluster-node1:/data/ipfs-cluster
    environment:
      - IPFS_CLUSTER_PATH=/data/ipfs-cluster
    ports:
      - "9094:9094"
      - "9095:9095"
    command: ["ipfs-cluster-service", "daemon"]

  cluster-node2:
    container_name: cluster-node2
    image: ipfs/ipfs-cluster:latest
    restart: unless-stopped
    volumes:
      - ./cluster-data/cluster-node2:/data/ipfs-cluster
    environment:
      - IPFS_CLUSTER_PATH=/data/ipfs-cluster
    ports:
      - "9096:9094"
      - "9097:9095"
    command: ["ipfs-cluster-service", "daemon"]

  cluster-node3:
    container_name: cluster-node3
    image: ipfs/ipfs-cluster:latest
    restart: unless-stopped
    volumes:
      - ./cluster-data/cluster-node3:/data/ipfs-cluster
    environment:
      - IPFS_CLUSTER_PATH=/data/ipfs-cluster
    ports:
      - "9098:9094"
      - "9099:9095"
    command: ["ipfs-cluster-service", "daemon"]

  cluster-node4:
    container_name: cluster-node4
    image: ipfs/ipfs-cluster:latest
    restart: unless-stopped
    volumes:
      - ./cluster-data/cluster-node4:/data/ipfs-cluster
    environment:
      - IPFS_CLUSTER_PATH=/data/ipfs-cluster
    ports:
      - "9100:9094"
      - "9101:9095"
    command: ["ipfs-cluster-service", "daemon"]

  cluster-node5:
    container_name: cluster-node5
    image: ipfs/ipfs-cluster:latest
    restart: unless-stopped
    volumes:
      - ./cluster-data/cluster-node5:/data/ipfs-cluster
    environment:
      - IPFS_CLUSTER_PATH=/data/ipfs-cluster
    ports:
      - "9102:9094"
      - "9103:9095"
    command: ["ipfs-cluster-service", "daemon"]

  cluster-node6:
    container_name: cluster-node6
    image: ipfs/ipfs-cluster:latest
    restart: unless-stopped
    volumes:
      - ./cluster-data/cluster-node6:/data/ipfs-cluster
    environment:
      - IPFS_CLUSTER_PATH=/data/ipfs-cluster
    ports:
      - "9104:9094"
      - "9105:9095"
    command: ["ipfs-cluster-service", "daemon"]

  cluster-node7:
    container_name: cluster-node7
    image: ipfs/ipfs-cluster:latest
    restart: unless-stopped
    volumes:
      - ./cluster-data/cluster-node7:/data/ipfs-cluster
    environment:
      - IPFS_CLUSTER_PATH=/data/ipfs-cluster
    ports:
      - "9106:9094"
      - "9107:9095"
    command: ["ipfs-cluster-service", "daemon"]

  cluster-node8:
    container_name: cluster-node8
    image: ipfs/ipfs-cluster:latest
    restart: unless-stopped
    volumes:
      - ./cluster-data/cluster-node8:/data/ipfs-cluster
    environment:
      - IPFS_CLUSTER_PATH=/data/ipfs-cluster
    ports:
      - "9108:9094"
      - "9109:9095"
    command: ["ipfs-cluster-service", "daemon"]

  cluster-node9:
    container_name: cluster-node9
    image: ipfs/ipfs-cluster:latest
    restart: unless-stopped
    volumes:
      - ./cluster-data/cluster-node9:/data/ipfs-cluster
    environment:
      - IPFS_CLUSTER_PATH=/data/ipfs-cluster
    ports:
      - "9110:9094"
      - "9111:9095"
    command: ["ipfs-cluster-service", "daemon"]

  cluster-node10:
    container_name: cluster-node10
    image: ipfs/ipfs-cluster:latest
    restart: unless-stopped
    volumes:
      - ./cluster-data/cluster-node10:/data/ipfs-cluster
    environment:
      - IPFS_CLUSTER_PATH=/data/ipfs-cluster
    ports:
      - "9112:9094"
      - "9113:9095"
    command: ["ipfs-cluster-service", "daemon"]

